# Generated by Django 5.2.17 on 2026-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('tiempo_maximo_respuesta', models.PositiveIntegerField(verbose_name='Tiempo máximo de respuesta (minutos)')),
                ('tiempo_maximo_resolucion', models.PositiveIntegerField(verbose_name='Tiempo máximo de resolución (minutos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Política SLA',
                'verbose_name_plural': 'Políticas SLA',
                'ordering': ['prioridad', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('prioridad',), name='uniq_sla_prioridad')],
            },
        ),
    ]
