# Generated by Django 5.2.17 on 2026-08-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('TOMADA', 'Tomada'), ('EN_EJECUCION', 'En ejecución'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('fecha_tomada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que fue tomada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tecnico', models.ForeignKey(blank=True, help_text='Se asigna cuando un técnico toma la oferta; puede ser nulo al publicarla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_tomadas', to='tecnicos.tecnico', verbose_name='Técnico que tomó la oferta')),
            ],
            options={
                'verbose_name': 'Oferta de ticket',
                'verbose_name_plural': 'Ofertas de ticket',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
