# Generated by Django 5.2.17 on 2026-08-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaticket',
            name='ticket',
            field=models.OneToOneField(help_text='Cada ticket puede tener como máximo una oferta.', on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddIndex(
            model_name='ofertaticket',
            index=models.Index(fields=['estado'], name='idx_oferta_estado'),
        ),
    ]
