# Generated by Django 5.2.17 on 2026-08-27 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Identificador único y corto de la sucursal.', max_length=20, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('encargados', models.ManyToManyField(blank=True, help_text='Usuarios encargados de la sucursal.', related_name='sucursales_encargadas', to=settings.AUTH_USER_MODEL, verbose_name='Encargados')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
