# Generated by Django 5.2.17 on 2026-08-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Documento de identificación')),
                ('descripcion', models.TextField(blank=True, help_text='Experiencia, notas u otra información relevante.', verbose_name='Información adicional')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('NO_DISPONIBLE', 'No disponible'), ('INACTIVO', 'Inactivo')], default='NO_DISPONIBLE', max_length=20, verbose_name='Estado / Disponibilidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='tecnicos', to='tecnicos.especialidad', verbose_name='Especialidades')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['usuario__username'],
                'indexes': [models.Index(fields=['estado'], name='idx_tecnico_estado')],
            },
        ),
    ]
