# Generated by Django 5.2.17 on 2026-08-27 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('sucursales', '0001_initial'),
        ('tecnicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='tecnicos.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('trabajo_realizado', models.TextField(blank=True, verbose_name='Trabajo realizado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo estimado')),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo final')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='ofertas.ofertaticket', verbose_name='Oferta')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='tecnicos.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación (1 a 5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de calificación')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='tecnicos.tecnico', verbose_name='Técnico')),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='tickets.ordentrabajo', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_calificacion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En revisión'), ('PUBLICADO', 'Publicado'), ('EN_EJECUCION', 'En ejecución'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('INCIDENCIA', 'Incidencia'), ('PREVENTIVO', 'Preventivo')], default='INCIDENCIA', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción de la falla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_limite_sla', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite según SLA')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('informacion_adicional', models.TextField(blank=True, verbose_name='Información adicional')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.categoria', verbose_name='Categoría')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.CreateModel(
            name='EvidenciaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Evidencia de ticket',
                'verbose_name_plural': 'Evidencias de ticket',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=30, verbose_name='Estado nuevo')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de ticket',
                'verbose_name_plural': 'Historial de tickets',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='idx_ticket_estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='idx_ticket_prioridad'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sucursal'], name='idx_ticket_sucursal'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='idx_orden_estado'),
        ),
    ]
